# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

parameters:
  - name: userpool
    type: string
    default: Azure Pipelines
    values:
    - Azure Pipelines
    - ubuntu-latest
  - name: docker-repo
    type: string
    default: hieub1875
  - name: docker-image
    type: string
    default: azure-demo

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Docker@2
  inputs:
    containerRegistry: 'hieu-docker-registry'
    command: 'login'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      pwd
      docker image ls
- task: Docker@2
  inputs:
    containerRegistry: 'hieu-docker-registry'
    repository: '${{ parameters.docker-repo }}/${{ parameters.docker-image }}'
    command: 'buildAndPush'
    Dockerfile: '**/AzureDockerfile'
